<?php

/**
 * @file
 * Support for 500px posts as media entities in Lightning.
 */

use Drupal\Core\Form\FormStateInterface;
use Drupal\lightning_core\OverrideHelper as Override;
use Drupal\lightning_media_d500px\Plugin\MediaEntity\Type\D500px;

/**
 * Implements hook_media_entity_type_info_alter().
 */
function lightning_media_d500px_media_entity_type_info_alter(array &$types) {
  $types['d500px']['input_match'] = [
    'constraint' => 'D500pxEmbedCode',
    'field_types' => [
      'string',
      'string_long',
    ],
  ];
  $types['d500px']['preview'] = TRUE;

  Override::pluginClass($types['d500px'], D500px::class);
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function lightning_media_d500px_form_media_d500px_form_alter(array &$form, FormStateInterface $form_state) {
  \Drupal::service('lightning_media.preview.embed_code')->alterForm($form, $form_state);
}

/**
 * Implements hook_inline_entity_form_entity_form_alter().
 */
function lightning_media_d500px_inline_entity_form_entity_form_alter(&$entity_form, FormStateInterface $form_state) {
  if ($entity_form['#entity_type'] == 'media' && $entity_form['#bundle'] == 'd500px') {
    \Drupal::service('lightning_media.preview.embed_code')->alterForm($entity_form, $form_state, $entity_form['#entity']);
  }
}

/**
 * Implements hook_entity_extra_field_info().
 */
function lightning_media_d500px_entity_extra_field_info() {
  return \Drupal::service('lightning_media.preview.embed_code')->extraFields('d500px');
}
